<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MirrorVM.Runtime</AssemblyName>
    <RootNamespace>MirrorVM</RootNamespace>
    <TargetFrameworks>net20;netstandard2.0;net9.0</TargetFrameworks>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
