<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net20;netcoreapp3.1;net481;net9.0</TargetFrameworks>
    <LangVersion>7.3</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\..\Release\Samples\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MirrorVM.Runtime\MirrorVM.Runtime.csproj" />
  </ItemGroup>
</Project>
